version: "3.8"

services:
  ai-engine:
    container_name: mule-hunter-ai
    build:
      context: ./ai-engine
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./shared-data:/app/shared-data
    networks:
      - mulehunter-net

  visual-analytics:
    container_name: visual-analytics
    build:
      context: ./visual-analytics/eif_v_2
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - mulehunter-net

  security-forensics:
    container_name: security-forensics
    build:
      context: ./security-forensics
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - mulehunter-net

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      visual.internal-api-key: dummy
      security.service.url: http://security-forensics:8081
      ai.service.url: http://ai-engine:8001
      visual.service.url: http://visual-analytics:8000
      spring.data.mongodb.uri: ${MONGODB_URI}
    depends_on:
      - security-forensics
      - ai-engine
      - visual-analytics
    networks:
      - mulehunter-net

  control-tower:
    container_name: control-tower-app
    build:
      context: ./control-tower
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_BASE_URL: http://localhost:8082
        NEXTAUTH_SECRET: dummy
        NEXTAUTH_URL: http://localhost:3000
        JWT_SECRET: dummy
        NEXT_PUBLIC_EMAILJS_SERVICE_ID: dummy
        NEXT_PUBLIC_EMAILJS_TEMPLATE_ID: dummy
        NEXT_PUBLIC_EMAILJS_PUBLIC_KEY: dummy
        MONGODB_URI: ${MONGODB_URI}
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - mulehunter-net

networks:
  mulehunter-net:
    driver: bridge