spring.application.name=backend
jwt.secret=hsdhsu68283hsdbbsdju28e77382327920oddn83t8y3i2nhw8dyy73298329ndw28723h
visual.internal-api-key=visual-analytics-secret-123
spring.data.mongodb.uri=mongodb+srv://rupali:MuleHunterRupali123@cluster0.pjwljsk.mongodb.net/test
security.service.url=http://localhost:8081
ai.service.url=http://localhost:8001
eif.service.url=http://localhost:8000
visual.service.url=http://localhost:8000
spring.mvc.async.request-timeout=-1
server.port=8082
