FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    g++ \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install numpy==1.26.4 Cython==0.29.36 wheel setuptools

ENV CXX=g++
ENV CFLAGS="-std=c++11"
ENV CXXFLAGS="-std=c++11"

RUN pip install --no-build-isolation eif==2.0.2

RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    scikit-learn \
    pandas \
    joblib \
    pydantic

COPY app ./app
COPY models ./models

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]