/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness + dependency status */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Email + password → MFA challenge */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oauth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Google OAuth code exchange → MFA challenge */
        post: operations["oauthGoogle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Begin TOTP enrolment → otpauth provisioning URI (rendered as QR client-side)
         * @description Returns the `otpauth://` URI exactly once. The secret is never logged and
         *     never re-displayed. Regenerating produces a **different** secret every time.
         */
        post: operations["mfaEnroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** TOTP code + mfa_token → access + refresh JWT */
        post: operations["mfaVerify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate refresh token */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current profile, role, and active sessions */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a specific session */
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cursor-paginated, server-sorted alert queue */
        get: operations["listAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One alert */
        get: operations["getAlert"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Acknowledge / assign / resolve / mark false-positive */
        patch: operations["updateAlert"];
        trace?: never;
    };
    "/api/v1/alerts/{id}/escalate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Escalate an alert to MLRO */
        post: operations["escalateAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account lookup (cursor-paginated, server-sorted) */
        get: operations["listAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account profile (PII masked by role) */
        get: operations["getAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/score-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** WarmthScore trajectory + SHAP per point */
        get: operations["getScoreHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account transactions (cursor-paginated) */
        get: operations["getAccountTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** IMEI/SIM event history */
        get: operations["getAccountDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current S1–S6 signal breakdown */
        get: operations["getAccountSignals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Freeze / restrict / KYC-review (MLRO; server re-checks role) */
        post: operations["accountAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/neighborhood/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Force-directed neighborhood subgraph */
        get: operations["getNeighborhood"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/patterns/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detected layering / round-trip / structuring subgraphs */
        get: operations["getPatterns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/freeze-cluster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Freeze a selected node set (MLRO); propagates taint */
        post: operations["freezeCluster"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recruiters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detected coordinators + campaign scale class */
        get: operations["listRecruiters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recruiters/{id}/campaign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full fan-out subgraph for a recruiter */
        get: operations["getRecruiterCampaign"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recruiters/{id}/freeze-campaign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** One-click network freeze (MLRO); propagates taint */
        post: operations["freezeCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cases */
        get: operations["listCases"];
        put?: never;
        /** Open a case (optionally from an alert) */
        post: operations["createCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One case */
        get: operations["getCase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Transition a case (state change is audit-logged) */
        patch: operations["updateCase"];
        trace?: never;
    };
    "/api/v1/cases/{id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add an analyst note */
        post: operations["addCaseNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach a graph snapshot / timeline export */
        post: operations["attachEvidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full state-transition history */
        get: operations["getCaseActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autostr/{case_id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate the three evidence packages (async job) */
        post: operations["generateStr"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autostr/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job status: ASSEMBLING → SIGNING → SEALED */
        get: operations["getStrJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autostr/{case_id}/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sealed packages (with document fingerprint chip) */
        get: operations["listPackages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autostr/packages/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream a package file (server-side authz; audit-logged) */
        get: operations["downloadPackage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autostr/packages/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** MLRO approval → mark submitted (countersignature) */
        post: operations["approvePackage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Append-only, HMAC-chained audit entries */
        get: operations["getAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chain-integrity check → "Ledger intact ✓ (N entries)" */
        get: operations["verifyAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scheduled report registry */
        get: operations["getReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/fairness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bias / false-positive metrics by segment (DPDP story) */
        get: operations["getFairness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users (SYS_ADMIN) */
        get: operations["listUsers"];
        put?: never;
        /** Invite a user (SYS_ADMIN; no public signup) */
        post: operations["inviteUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change role / disable / force MFA reset (SYS_ADMIN) */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/api/v1/admin/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service status strip (SYS_ADMIN) */
        get: operations["adminHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-screen canned prompts (3 chips) */
        get: operations["assistantSuggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask the on-prem assistant (SSE streamed reply) */
        post: operations["assistantChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feed/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Replay buffer for page load / WS backfill */
        get: operations["getRecentFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/pulse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rolling operational KPIs */
        get: operations["getPulse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket: multiplexed event stream (documented here for the contract)
         * @description Upgrade to WebSocket. Client subscribes to channels
         *     (`transactions`, `alerts`, `scores`, `metrics`). Server pushes
         *     `Event` objects with monotonic ids; gaps are backfilled via
         *     `/feed/recent?after_id=`.
         */
        get: operations["stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sim/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Load / start / pause a scenario (SYS_ADMIN only) */
        post: operations["controlScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sim/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current simulator status */
        get: operations["getSimStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Meta: {
            /** @description Opaque cursor for the next page; null when exhausted. */
            cursor?: string | null;
            total?: number | null;
        };
        Problem: {
            /**
             * Format: uri
             * @default about:blank
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** @description Machine-readable error code, e.g. mfa_required, rate_limited. */
            code?: string;
        };
        HealthEnvelope: {
            data: {
                /** @enum {string} */
                status: "ok" | "degraded";
                version: string;
                dependencies: {
                    [key: string]: {
                        /** @enum {string} */
                        status?: "up" | "down" | "disabled";
                        detail?: string;
                    };
                };
            };
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        MfaChallenge: {
            /** @constant */
            mfa_required: true;
            /** @description Short-lived token to bind the MFA step. */
            mfa_token: string;
            /** @description False on first login → client must enrol first. */
            mfa_enrolled: boolean;
        };
        MfaEnrolment: {
            /** @description otpauth:// provisioning URI. Appears in exactly this one response; never re-displayed. */
            otpauth_uri: string;
        };
        MfaVerifyRequest: {
            mfa_token: string;
            code: string;
        };
        TokenPair: {
            access_token: string;
            refresh_token: string;
            /** @constant */
            token_type: "bearer";
            /** @description Access token TTL in seconds. */
            expires_in: number;
        };
        /** @enum {string} */
        Role: "MLRO" | "FRAUD_ANALYST" | "COMPLIANCE_AUDITOR" | "SYS_ADMIN";
        Me: {
            id: string;
            /** Format: email */
            email: string;
            name: string;
            role: components["schemas"]["Role"];
            mfa_active: boolean;
            /** Format: date-time */
            mfa_active_since?: string | null;
            sessions: components["schemas"]["Session"][];
        };
        Session: {
            id: string;
            device: string;
            ip: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_seen_at?: string;
            current: boolean;
        };
        /** @enum {string} */
        Severity: "CLEAN" | "WARMING" | "HOT" | "CRITICAL" | "IMMINENT";
        /** @enum {string} */
        AlertStatus: "NEW" | "ACKNOWLEDGED" | "ASSIGNED" | "ESCALATED" | "RESOLVED" | "FALSE_POSITIVE";
        ShapSignal: {
            /** @example S3 */
            code: string;
            /** @example Round-trip ratio 0.94 */
            label: string;
            /** @description Warmth points contributed. */
            contribution: number;
        };
        Alert: {
            id: string;
            /** @description Masked account reference (PII-safe). */
            account_ref: string;
            warmth_score: number;
            severity: components["schemas"]["Severity"];
            status: components["schemas"]["AlertStatus"];
            top_signals: components["schemas"]["ShapSignal"][];
            /** Format: date-time */
            first_signal_at: string;
            /**
             * Format: date-time
             * @description STR filing deadline (PMLA §12) — the ticking clock.
             */
            sla_deadline?: string | null;
            taint_linked: boolean;
            assignee?: string | null;
            case_id?: string | null;
        };
        AlertListEnvelope: {
            data: components["schemas"]["Alert"][];
            meta: components["schemas"]["Meta"];
        };
        AlertUpdate: {
            /** @enum {string} */
            action?: "acknowledge" | "assign" | "resolve" | "mark_false_positive";
            assignee?: string;
            note?: string;
        };
        Event: {
            /** @description Monotonic event id. */
            id: number;
            /** @enum {string} */
            type: "transaction.posted" | "account.created" | "device.registered" | "kyc.updated" | "alert.raised" | "score.updated";
            /** Format: date-time */
            ts: string;
            payload: {
                [key: string]: unknown;
            };
        };
        EventListEnvelope: {
            data: components["schemas"]["Event"][];
            meta: components["schemas"]["Meta"];
        };
        Pulse: {
            tx_per_sec: number;
            active_alerts: number;
            accounts_watched: number;
            avg_score: number;
            /** Format: date-time */
            updated_at: string;
        };
        AccountSummary: {
            id: string;
            /** @description Masked reference for lists. */
            account_ref: string;
            /** @description Holder name, masked unless the role may view PII. */
            holder: string;
            branch?: string;
            segment?: string;
            warmth_score: number;
            severity: components["schemas"]["Severity"];
            status: components["schemas"]["AccountStatus"];
            tainted: boolean;
        };
        Account: components["schemas"]["AccountSummary"] & {
            ifsc?: string;
            kyc_status: string;
            status_reason?: string | null;
            response_tier: number;
            taint_score?: number;
            /** Format: date-time */
            opened_at: string;
            /** Format: date-time */
            last_active: string;
            /** @description True when the caller's role only sees masked PII. */
            pii_masked?: boolean;
            top_signals?: components["schemas"]["ShapSignal"][];
        };
        /** @enum {string} */
        AccountStatus: "ACTIVE" | "WATCH" | "KYC_HOLD" | "RESTRICTED" | "FROZEN";
        AccountListEnvelope: {
            data: components["schemas"]["AccountSummary"][];
            meta: components["schemas"]["Meta"];
        };
        ScorePoint: {
            /** Format: date-time */
            ts: string;
            score: number;
            severity: components["schemas"]["Severity"];
            shap?: components["schemas"]["ShapSignal"][];
        };
        AccountTransaction: {
            id: string;
            /** Format: date-time */
            ts: string;
            /** @description Masked counterparty, or null if external. */
            counterparty_ref?: string | null;
            amount: number;
            /** @enum {string} */
            direction: "IN" | "OUT";
            channel: string;
            description?: string | null;
        };
        TransactionListEnvelope: {
            data: components["schemas"]["AccountTransaction"][];
            meta: components["schemas"]["Meta"];
        };
        DeviceEvent: {
            /** @description Masked IMEI (last 4 shown). */
            imei: string;
            event_type: string;
            /** Format: date-time */
            registered_at: string;
        };
        SignalBreakdown: {
            score: number;
            /** @description Raw S1–S6 values in [0,1]. */
            signals: {
                [key: string]: number;
            };
            shap: components["schemas"]["ShapSignal"][];
        };
        AccountAction: {
            /** @enum {string} */
            action: "freeze" | "restrict" | "kyc_review" | "unfreeze";
            reason?: string;
        };
        GraphNode: {
            id: string;
            account_ref: string;
            holder?: string;
            warmth_score: number;
            severity: components["schemas"]["Severity"];
            status?: components["schemas"]["AccountStatus"];
            tainted: boolean;
            is_recruiter?: boolean;
        };
        GraphEdge: {
            source: string;
            target: string;
            /** @description Summed transaction value (edge weight). */
            value: number;
            count: number;
        };
        Graph: {
            root: string;
            nodes: components["schemas"]["GraphNode"][];
            edges: components["schemas"]["GraphEdge"][];
        };
        PatternMatch: {
            anchor: string;
            anchor_id: string;
            severity: components["schemas"]["Severity"];
            warmth_score?: number;
            nodes: components["schemas"]["GraphNode"][];
            edges: components["schemas"]["GraphEdge"][];
        };
        FreezeResult: {
            /** @description Accounts frozen. */
            frozen: number;
            /** @description Downstream accounts tainted by propagation. */
            tainted: number;
            account_refs?: string[];
        };
        Recruiter: {
            id: string;
            account_ref: string;
            holder?: string;
            branch?: string;
            warmth_score?: number;
            downstream_count: number;
            total_distributed?: number;
            /** @enum {string} */
            scale_class: "FACILITATOR" | "COORDINATOR" | "INDUSTRIAL_ORCHESTRATOR" | "NATIONAL_SYNDICATE";
            campaign?: string | null;
        };
        RecruiterCampaign: {
            recruiter: {
                id?: string;
                account_ref?: string;
                scale_class?: string;
                downstream_count?: number;
            };
            mule_ids: string[];
            nodes: components["schemas"]["GraphNode"][];
            edges: components["schemas"]["GraphEdge"][];
        };
        /** @enum {string} */
        CaseStatus: "OPEN" | "UNDER_REVIEW" | "PENDING_MLRO" | "CLOSED_CONFIRMED_MULE" | "CLOSED_FALSE_POSITIVE";
        CaseCreate: {
            title: string;
            account_ids?: string[];
            /** @description Open from an alert (links account + alert). */
            alert_id?: string;
        };
        CaseNote: {
            id: string;
            author: string;
            body: string;
            /** Format: date-time */
            created_at: string;
        };
        CaseActivity: {
            actor: string;
            action: string;
            from_status?: string | null;
            to_status?: string | null;
            /** Format: date-time */
            at: string;
        };
        Case: {
            id: string;
            title: string;
            status: components["schemas"]["CaseStatus"];
            account_ids: string[];
            alert_ids?: string[];
            evidence?: {
                [key: string]: unknown;
            }[];
            created_by: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
            notes?: components["schemas"]["CaseNote"][];
        };
        CaseListEnvelope: {
            data: components["schemas"]["Case"][];
            meta: components["schemas"]["Meta"];
        };
        StrJob: {
            id: string;
            case_id: string;
            /** @enum {string} */
            status: "ASSEMBLING" | "SIGNING" | "SEALED" | "FAILED";
            /** Format: date-time */
            created_at: string;
            package_ids?: string[];
            error?: string | null;
        };
        PackageSummary: {
            id: string;
            /** @enum {string} */
            type: "FIU_STR_XML" | "CBI_PDF" | "RBI_JSON";
            filename: string;
            fingerprint: string;
            /** Format: date-time */
            generated_at: string;
            /** @enum {string} */
            status: "SEALED" | "SUBMITTED";
            approved_by?: string | null;
            /** Format: date-time */
            approved_at?: string | null;
        };
        AuditRecord: {
            seq: number;
            /** Format: date-time */
            at: string;
            actor: string;
            action: string;
            target: string;
            detail?: {
                [key: string]: unknown;
            };
            /** @description Last 8 chars of the entry hash (chain marker, not key material). */
            fingerprint: string;
        };
        AuditListEnvelope: {
            data: components["schemas"]["AuditRecord"][];
            meta: components["schemas"]["Meta"];
        };
        LedgerVerification: {
            intact: boolean;
            entries: number;
            broken_at?: number | null;
        };
        ComplianceReport: {
            id: string;
            name: string;
            cadence: string;
            /** Format: date-time */
            last_generated: string | null;
        };
        Fairness: {
            overall_fp_rate: number;
            segments: {
                segment?: string;
                accounts?: number;
                flagged?: number;
                false_positive_rate?: number;
            }[];
        };
        AdminUser: {
            id: string;
            /** Format: email */
            email: string;
            name: string;
            role: components["schemas"]["Role"];
            disabled: boolean;
            mfa_active: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        UserInvite: {
            /** Format: email */
            email: string;
            name: string;
            role: components["schemas"]["Role"];
            /** @description Optional initial password; user re-enrols MFA on first login. */
            temp_password?: string;
        };
        UserUpdate: {
            role?: components["schemas"]["Role"];
            disabled?: boolean;
            force_mfa_reset?: boolean;
        };
        ScenarioControl: {
            /** @enum {string} */
            command: "load" | "start" | "pause" | "reset";
            /** @description Campaign name (YAML file stem), required for load. */
            scenario?: string;
            seed?: number;
        };
        SimStatus: {
            /** @enum {string} */
            state: "idle" | "loaded" | "running" | "paused";
            scenario: string | null;
            seed: number | null;
            /** @description Events emitted so far. */
            emitted: number;
            tx_per_sec: number;
            available_scenarios?: string[];
        };
    };
    responses: {
        /** @description RFC-7807 problem+json error. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up; reports each dependency. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthEnvelope"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Credentials valid; MFA required. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MfaChallenge"];
                    };
                };
            };
            401: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    oauthGoogle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                    /** Format: uri */
                    redirect_uri?: string;
                };
            };
        };
        responses: {
            /** @description OAuth valid; MFA required. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MfaChallenge"];
                    };
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    mfaEnroll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provisioning URI issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MfaEnrolment"];
                    };
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    mfaVerify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaVerifyRequest"];
            };
        };
        responses: {
            /** @description MFA verified; tokens issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TokenPair"];
                    };
                };
            };
            401: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refresh_token: string;
                };
            };
        };
        responses: {
            /** @description New token pair (old refresh token revoked). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TokenPair"];
                    };
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Me"];
                    };
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Problem"];
        };
    };
    listAlerts: {
        parameters: {
            query?: {
                status?: components["schemas"]["AlertStatus"];
                severity?: components["schemas"]["Severity"];
                sort?: "score_desc" | "score_asc" | "newest" | "sla_soonest";
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of alerts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertListEnvelope"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    getAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alert detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Alert"];
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    updateAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertUpdate"];
            };
        };
        responses: {
            /** @description Updated alert. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Alert"];
                    };
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    escalateAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    note?: string;
                };
            };
        };
        responses: {
            /** @description Escalated alert. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Alert"];
                    };
                };
            };
            403: components["responses"]["Problem"];
        };
    };
    listAccounts: {
        parameters: {
            query?: {
                /** @description Match account ref or holder. */
                query?: string;
                risk_tier?: components["schemas"]["Severity"];
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of account summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountListEnvelope"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Account"];
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getScoreHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Score history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ScorePoint"][];
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getAccountTransactions: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of transactions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionListEnvelope"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getAccountDevices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DeviceEvent"][];
                    };
                };
            };
        };
    };
    getAccountSignals: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signal breakdown. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SignalBreakdown"];
                    };
                };
            };
        };
    };
    accountAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountAction"];
            };
        };
        responses: {
            /** @description Updated account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Account"];
                    };
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    getNeighborhood: {
        parameters: {
            query?: {
                hops?: number;
            };
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nodes + edges within N hops. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Graph"];
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getPatterns: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: "round_trip" | "layering" | "structuring" | "velocity" | "any";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching pattern subgraphs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PatternMatch"][];
                    };
                };
            };
        };
    };
    freezeCluster: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    account_ids: string[];
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Freeze result + taint summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FreezeResult"];
                    };
                };
            };
            403: components["responses"]["Problem"];
        };
    };
    listRecruiters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detected recruiters. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Recruiter"][];
                    };
                };
            };
        };
    };
    getRecruiterCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaign subgraph. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RecruiterCampaign"];
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    freezeCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Freeze result + taint summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FreezeResult"];
                    };
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    listCases: {
        parameters: {
            query?: {
                status?: components["schemas"]["CaseStatus"];
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of cases. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseListEnvelope"];
                };
            };
        };
    };
    createCase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseCreate"];
            };
        };
        responses: {
            /** @description Created case. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Case"];
                    };
                };
            };
        };
    };
    getCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Case detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Case"];
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    updateCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    status?: components["schemas"]["CaseStatus"];
                    title?: string;
                };
            };
        };
        responses: {
            /** @description Updated case. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Case"];
                    };
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    addCaseNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    body: string;
                };
            };
        };
        responses: {
            /** @description Note added. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CaseNote"];
                    };
                };
            };
        };
    };
    attachEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    kind: "graph_snapshot" | "timeline_export" | "note";
                    ref: string;
                    label?: string;
                };
            };
        };
        responses: {
            /** @description Updated case. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Case"];
                    };
                };
            };
        };
    };
    getCaseActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activity log. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CaseActivity"][];
                    };
                };
            };
        };
    };
    generateStr: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StrJob"];
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getStrJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StrJob"];
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listPackages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Packages. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PackageSummary"][];
                    };
                };
            };
        };
    };
    downloadPackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    approvePackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approved package. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PackageSummary"];
                    };
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    getAudit: {
        parameters: {
            query?: {
                actor?: string;
                action?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of audit entries (no key material). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditListEnvelope"];
                };
            };
        };
    };
    verifyAudit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification result (boolean + count only, never the key). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LedgerVerification"];
                    };
                };
            };
        };
    };
    getReports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Report registry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ComplianceReport"][];
                    };
                };
            };
        };
    };
    getFairness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fairness metrics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Fairness"];
                    };
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminUser"][];
                    };
                };
            };
            403: components["responses"]["Problem"];
        };
    };
    inviteUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserInvite"];
            };
        };
        responses: {
            /** @description Invited user. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminUser"];
                    };
                };
            };
            403: components["responses"]["Problem"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Updated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminUser"];
                    };
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    adminHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-service status lamps. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            [key: string]: {
                                /** @enum {string} */
                                status?: "up" | "down" | "disabled";
                                detail?: string;
                            };
                        };
                    };
                };
            };
            403: components["responses"]["Problem"];
        };
    };
    assistantSuggestions: {
        parameters: {
            query?: {
                screen?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Suggestion chips. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: string[];
                    };
                };
            };
        };
    };
    assistantChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    message: string;
                    screen_context?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description text/event-stream of reply tokens; degrades to an 'unavailable' event when Ollama is offline. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    getRecentFeed: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Return events with id greater than this (backfill). */
                after_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent events (monotonic ids). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListEnvelope"];
                };
            };
        };
    };
    getPulse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Live KPIs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Pulse"];
                    };
                };
            };
        };
    };
    stream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching Protocols (WebSocket). */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    controlScenario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioControl"];
            };
        };
        responses: {
            /** @description Simulator status after the command. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SimStatus"];
                    };
                };
            };
            403: components["responses"]["Problem"];
        };
    };
    getSimStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Simulator status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SimStatus"];
                    };
                };
            };
        };
    };
}
